apply plugin: 'com.android.application'

//生成打包时间
def releaseTime() {
    return new Date().format("yyyy-MM-dd", TimeZone.getTimeZone("UTC"))
}

android {
    namespace 'com.sn.blackdianqi'
    compileSdk 36

    defaultConfig {
        applicationId = "com.sn.blackdianqi"
        minSdk = 26
        targetSdk = 36
        versionCode = 35
        versionName = "1.35"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }

        // 默认渠道为官网
        manifestPlaceholders = [UMENG_CHANNEL_VALUE: "official"]

    }

    flavorDimensions = ["channel"]
    productFlavors {
        google {}
    }

    signingConfigs {
        debug {
            v1SigningEnabled true
            v2SigningEnabled true
            storeFile file('./keystore/lykj_release.jks')
            storePassword '123456'
            keyAlias 'lykj'
            keyPassword '123456'
        }
        release {
            v1SigningEnabled true
            v2SigningEnabled true
            storeFile file('./keystore/lykj_release.jks')
            storePassword '123456'
            keyAlias 'lykj'
            keyPassword '123456'
        }
    }

    buildTypes {
        debug {
            buildConfigField "boolean", "Debuggable", "true"
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
        release {
            buildConfigField "boolean", "Debuggable", "true"
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    applicationVariants.configureEach { variant ->
        if (variant.buildType.name != "release") {
            return
        }
        variant.outputs.configureEach { output ->
            output.outputFileName = "Motion-bed_${variant.versionName}_${releaseTime()}_${variant.flavorName}.apk"
        }
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
        dataBinding true
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.code.gson:gson:2.2.4'
    implementation 'com.google.android.material:material:1.4.0'

    implementation 'net.frakbot:jumpingbeans:1.3.0'

    // 时间空间选择
    implementation 'com.github.gzu-liyujiang.AndroidPicker:Common:4.1.1'
    implementation 'com.github.gzu-liyujiang.AndroidPicker:WheelPicker:4.1.1'
    implementation 'com.github.gzu-liyujiang.AndroidPicker:WheelView:4.1.1'

    // 日历 https://gitee.com/huanghaibin_dev/CalendarView
    implementation 'com.haibin:calendarview:3.7.1'

    // 折线图 https://github.com/lecho/hellocharts-android
    implementation 'com.github.lecho:hellocharts-library:1.5.8@aar'

    // eventbus
    implementation 'org.greenrobot:eventbus:3.3.1'

    /**权限*/
    implementation 'com.github.getActivity:XXPermissions:28.0'

    // test
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
